### ISSUE TITLE
Error when update field mapped as boolean on Doctrine

### ISSUE THREAD

**Issue by silasrm** [FriendsOfSymfony/FOSElasticaBundle#1382]
Hi,

If I change any property in my entity and try to update (persist/flush with doctrine), this error occurs:

> Current token (VALUE_NUMBER_INT) not of boolean type↵ at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1d349bde; line: 1, column: 754]

In my entity has many fields mapped with type boolean, but doctrine save using tinyint (1/0).

`@ORM\Column(name="referencia", type="boolean")`

Any idea to change force to convert to boolean before try to update in elasticsearch?

**Comment by silasrm** [comment]
I remove others fields except ID and Name (nome) but this error continue to occurs. Following the ES mapping json:

```
{
    "XXXXX_2018-01-10-001800": {
        "aliases": {
            "XXXXX": {}
        },
        "mappings": {
            "pessoa": {
                "_meta": {
                    "model": "ESUAS\\BaseBundle\\Entity\\Pessoa"
                },
                "dynamic_date_formats": [],
                "properties": {
                    "id": {
                        "type": "long"
                    },
                    "nome": {
                        "analyzer": "ngram_analyzer",
                        "boost": 10.0,
                        "type": "text"
                    },
                    "suggest": {
                        "analyzer": "simple",
                        "max_input_length": 50,
                        "preserve_position_increments": true,
                        "preserve_separators": true,
                        "type": "completion"
                    }
                }
            }
        },
        "settings": {
            "index": {
                "analysis": {
                    "analyzer": {
                        "index_analyzer": {
                            "filter": [
                                "lowercase"
                            ],
                            "tokenizer": "standard",
                            "type": "custom"
                        },
                        "my_analyzer": {
                            "language": "English",
                            "type": "snowball"
                        },
                        "ngram_analyzer": {
                            "filter": [
                                "lowercase",
                                "name_ngram"
                            ],
                            "tokenizer": "keyword",
                            "type": "custom"
                        },
                        "search_analyzer": {
                            "filter": [
                                "standard",
                                "lowercase"
                            ],
                            "tokenizer": "standard",
                            "type": "custom"
                        },
                        "starts_with_analyzer": {
                            "filter": [
                                "lowercase"
                            ],
                            "tokenizer": "keyword",
                            "type": "custom"
                        }
                    },
                    "filter": {
                        "my_ngram": {
                            "max_gram": "5",
                            "min_gram": "3",
                            "type": "nGram"
                        },
                        "name_ngram": {
                            "max_gram": "20",
                            "min_gram": "1",
                            "type": "edge_ngram"
                        }
                    }
                },
                "creation_date": "1515543481116",
                "number_of_replicas": "1",
                "number_of_shards": "5",
                "provided_name": "XXXXX_2018-01-10-001800",
                "uuid": "NeQ4K9AFTByhJ2WCt6pr3Q",
                "version": {
                    "created": "6010199"
                }
            }
        }
    }
}
```

**Comment by silasrm** [comment]
Stack trace as string:

> #0 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Request.php(193): Elastica\Transport\Http->exec(Object(Elastica\Request), Array) #1 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Client.php(683): Elastica\Request->send() #2 /home/suascom/apps/mandirituba/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Client.php(50): Elastica\Client->request('_bulk', 'POST', '{"update":{"_in...', Array, 'application/x-n...') #3 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Bulk.php(357): FOS\ElasticaBundle\Elastica\Client->request('_bulk', 'POST', '{"update":{"_in...', Array, 'application/x-n...') #4 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Client.php(328): Elastica\Bulk->send() #5 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Index.php(133): Elastica\Client->updateDocuments(Array) #6 /home/suascom/apps/mandirituba/vendor/ruflin/elastica/lib/Elastica/Type.php(181): Elastica\Index->updateDocuments(Array) #7 /home/suascom/apps/mandirituba/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php(125): Elastica\Type->updateDocuments(Array) #8 /home/suascom/apps/mandirituba/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php(208): FOS\ElasticaBundle\Persister\ObjectPersister->replaceMany(Array) #9 /home/suascom/apps/mandirituba/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php(183): FOS\ElasticaBundle\Doctrine\Listener->persistScheduled() #10 /home/suascom/apps/mandirituba/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php(61): FOS\ElasticaBundle\Doctrine\Listener->postFlush(Object(Doctrine\ORM\Event\PostFlushEventArgs)) #11 /home/suascom/apps/mandirituba/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3341): Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('postFlush', Object(Doctrine\ORM\Event\PostFlushEventArgs)) #12 /home/suascom/apps/mandirituba/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\ORM\UnitOfWork->dispatchPostFlushEvent() #13 /home/suascom/apps/mandirituba/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(358): Doctrine\ORM\UnitOfWork->commit(NULL) #14 /home/suascom/apps/mandirituba/var/cache/prod/appProdProjectContainer.php(6978): Doctrine\ORM\EntityManager->flush(NULL) #15 /home/suascom/apps/mandirituba/src/ESUAS/BaseBundle/Services/Pessoa.php(95): DoctrineORMEntityManager_000000006ce50cdd00000000372f489df021b4d5d103254e02f4b381c6c0691a->flush() #16 /home/suascom/apps/mandirituba/src/ESUAS/BaseBundle/Controller/PessoaController.php(333): ESUAS\BaseBundle\Services\Pessoa->update(Object(ESUAS\BaseBundle\Entity\Pessoa)) #17 [internal function]: ESUAS\BaseBundle\Controller\PessoaController->fotoAction('2576') #18 /home/suascom/apps/mandirituba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(153): call_user_func_array(Array, Array) #19 /home/suascom/apps/mandirituba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #20 /home/suascom/apps/mandirituba/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(169): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /home/suascom/apps/mandirituba/web/app.php(16): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #22 {main} [] []

**Comment by silasrm** [comment]
Solved in https://github.com/ruflin/Elastica/issues/1435#event-1449863221
